version: '3'
services:
  richi-nginx:
    build:
      context: ./docker
      dockerfile: nginx.docker
    volumes:
      - .:/app
    ports:
      - '${NGINX_HOST_PORT}:80'
    depends_on:
      - richi-php-fpm
    restart: always
  richi-php-fpm:
    build:
      context: ./docker
      dockerfile: php-fpm.docker
    volumes:
      - .:/app
    environment:
      APP_DEBUG: 1
    restart: always
  richi-php-cli:
    build:
      context: ./docker
      dockerfile: php-cli.docker
    volumes:
      - .:/app
      - composer:/root/.composer/cache
    ports:
      - '${PHP_CLI_XDEBUG_HOST_PORT}:9003'
    environment:
      APP_DEBUG: 1
      PHP_IDE_CONFIG: 'serverName=Docker'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
  richi-node:
    build:
      context: ./docker
      dockerfile: node.docker
    volumes:
      - .:/app
      - npm:/root/.npm
  richi-mysql:
    image: mysql:5.7
    volumes:
      - mysql:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d
    ports:
      - '${DATABASE_HOST_PORT}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    restart: always
volumes:
  composer:
  mysql:
  npm:
